[package]
name = "web3mq_mls"
authors = ["Web3MQ"]
version = "0.1.0"
edition = "2021"
license = "MIT"
readme = "./README.md"
keywords = ["MLS", "Web3MQ", "RFC9420", "Encryption", "E2EE"]

[dependencies]
base64 = "0.21.5"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"

openmls = "0.5"
openmls_traits = "0.2"
openmls_rust_crypto = "0.2"
openmls_basic_credential = "0.2"

# anyhow = "1"
# thiserror = "1"
# chrono = "^0.4"

# Only required for tests.
# rand = { version = "0.8", optional =ƒ true }

[dev-dependencies]
web3mq_mls = { path = "." }
